"""empty message

Revision ID: 0626edde4105
Revises: 1ded77de75dc
Create Date: 2025-05-06 21:50:05.057939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0626edde4105'
down_revision = '1ded77de75dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###
